# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: And Also Much Cattle
email: cattle4dayz@gmail.com
description: And Also Much Cattle is a webcomic of the Bible, Christianity, and puns by Karly Nelson, with contributions from Caroline Grossman and Kristen O'Neal.
baseurl: "/andalsomuchcattle" # the subpath of your site, e.g. /blog
url: "http://karlynelson.com" # the base hostname & protocol for your site

# Gems
gems:
  -jekyll-paginate

# Build settings
markdown: kramdown

# Pagination
paginate: 1
